### ISSUE TITLE
1.16.2 colors issue

### ISSUE THREAD

**Issue by arturek1666** [AlessioDP/OreAnnouncer#53] opened 2020-09-01 10:11 UTC
Every time player mine I will get kicked from server:
https://cdn.discordapp.com/attachments/617781540453220352/750288909463715901/14242142.PNG
I try my configuraction I try default same issue.

Using: 2.7.2 ore announcer.

**Comment by AlessioDP** [comment] 2020-09-01 10:15
Can you attach your configuration (messages.yml too) please.

Default configuration do not have the message that you showed in the screenshot

**Comment by arturek1666** [comment] 2020-09-01 10:37
https://gist.github.com/arturek1666/ee8b8a18587d6b910f8559019dbdfc9a

**Comment by arturek1666** [comment] 2020-09-01 10:37
I had used my custom one and default and similar result of error

**Comment by arturek1666** [comment] 2020-09-01 10:37
something with color: gold

**Comment by AlessioDP** [comment] 2020-09-02 22:05
The problem is that your JSON have new lines in the string: https://gist.github.com/arturek1666/ee8b8a18587d6b910f8559019dbdfc9a#file-oa-L67

You can use a JSON validator to check it ;)
Because this is not an issue related to the plugin itself I will close this issue, any question or help request feel free to ask it on Discord ;)

**Closed by AlessioDP** 2020-09-02 22:05 UTC
